name: CI/CD Pipeline

on:
  push:
    branches: [ "Sodah" ]
  pull_request:
    branches: [ "Sodah" ]
  
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Log errors if tests fail"
        required: true 
        default: "false"
      deploy:
        description: "Deploy to Azure after building Docker image"
        required: true 
        default: "false"

jobs:
  # Job 1:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code 
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv venv 
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest > pytest_output.log || exit 1

    - name: Upload error log if tests fail and log_errors is true
      if: failure() && github.event.inputs.log_errors == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: error_log
        path: pytest_output.log 

  # Job 2: 
  build: 
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_SODAH_USERNAME }}
          password: ${{ secrets.DOCKER_SODAH_PASSWORD }}
    
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_SODAH_USERNAME }}/myapp:latest -t ${{ secrets.DOCKER_SODAH_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_SODAH_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_SODAH_USERNAME }}/myapp:${{ github.sha }}

